# config.yaml
system:
  save_directory: "events"
  snapshot_on_event: true
  # ----------------------------
  # API SERVER CONFIG
  # ----------------------------
  api_host: "0.0.0.0"
  api_port: 8000
  
  token: ""
  MODEL_REPO: TommyNgx/YOLOv10-Fire-and-Smoke-Detection
  MODEL_FILE: best.pt
  #MODEL_REPO: Ultralytics/YOLOv8
  #MODEL_FILE: yolov8n.pt

  confidence_threshold: 0.3
  alert_frames_required: 1
  alert_classes:
    - fire
    - smoke
    #- person
  class_confidence_thresholds:
    fire: 0.3
    smoke: 0.5
    person: 0.6
  
  motion_ratio_threshold: 0.01
  motion_hold_time: 2

cameras:
  # - id: cam1
  #   name: Gate 7
  #   url: rtsp://admin:asdf123%40@192.168.176.202:554/Streaming/Channels/101?transport=tcp
  #   active: true

  # - id: cam2
  #   name: Main Gate
  #   url: rtsp://admin:asdf123%40@192.168.176.19:554/Streaming/Channels/101?transport=tcp
  #   active: true

  - id: old-fdy-2
    name: Old FDY 2
    url: rtsp://admin:asdf123%40@192.168.176.24:554/Streaming/Channels/1001?transport=tcp
    active: true

  # - id: poy-3
  #   name: POY 3
  #   url: rtsp://admin:asdf456%40@192.168.176.27:554/Streaming/Channels/2301?transport=tcp
  #   active: true

  - id: poy-4
    name: POY 4-7
    url: rtsp://admin:asdf456%40@192.168.176.28:554/Streaming/Channels/701?transport=tcp
    active: true

  - id: poy-4-29
    name: POY 4-29
    url: rtsp://admin:asdf456%40@192.168.176.28:554/Streaming/Channels/2901?transport=tcp
    active: true
  
  # - id: test-cam
  #   name: Test
  #   url: fire_video.mp4
  #   active: true

  # - id: cam3
  #   name: Gate 2
  #   url: rtsp://admin:asdf123%40@192.168.176.186:554/Streaming/Channels/101?transport=tcp
  #   active: true

  # - id: cam4
  #   name: Admin
  #   url: rtsp://admin:asdf123%40@192.168.176.161:554/Streaming/Channels/101?transport=tcp
  #   active: true

  # - id: cam5
  #   name: Gate 3
  #   url: rtsp://admin:asdf123%40@192.168.176.199:554/Streaming/Channels/101?transport=tcp
  #   active: true
